import type {
  Activity,
  CollectiveIntent,
  Destination,
  DestinationSeed,
  ItineraryItem,
  MockDestination,
  MockLocalActivity,
  MockMember,
  Provider,
  Review,
  Trip,
  UserProfile,
  Vote
} from "./types";

export const trips: Trip[] = [
  {
    id: "aspe",
    title: "Week-end nature en Vallée d'Aspe",
    destination: "Vallée d'Aspe, Pyrénées",
    image_url: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1600&q=80",
    dates: "Vendredi soir -> dimanche soir",
    duration: "2 jours",
    budget_min: 240,
    budget_max: 330,
    physical_level: "facile/intermédiaire",
    ambience_tags: ["calme", "nature", "découverte locale"],
    compatibility_score: 94,
    interested_count: 7,
    status: "Groupe en formation",
    description: "Une vallée de montagne authentique, idéale pour respirer, marcher doucement et partager un dîner local avec un petit groupe rassurant.",
    activities: ["Randonnée douce", "Ferme locale", "Dîner béarnais", "Rafting doux"]
  },
  {
    id: "fontainebleau",
    title: "Échappée forêt à Fontainebleau",
    destination: "Forêt de Fontainebleau",
    image_url: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
    dates: "Samedi",
    duration: "1 jour",
    budget_min: 30,
    budget_max: 80,
    physical_level: "facile",
    ambience_tags: ["débutant", "rencontre", "marche douce"],
    compatibility_score: 89,
    interested_count: 12,
    status: "Places ouvertes",
    description: "Une micro-aventure simple pour sortir de Paris, marcher sans pression et rencontrer des personnes qui ont la même envie de vert.",
    activities: ["Randonnée facile", "Pique-nique", "Rochers", "Café local"]
  },
  {
    id: "vercors",
    title: "Vercors slow adventure",
    destination: "Parc naturel du Vercors",
    image_url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1600&q=80",
    dates: "Week-end prochain",
    duration: "3 jours",
    budget_min: 220,
    budget_max: 360,
    physical_level: "intermédiaire",
    ambience_tags: ["montagne douce", "gîte", "fromagerie"],
    compatibility_score: 86,
    interested_count: 6,
    status: "Vote activités",
    description: "Un rythme lent, des paysages ouverts et une vraie immersion locale entre gîte, fromagerie et randonnée accessible.",
    activities: ["Randonnée", "Fromagerie", "Refuge", "Dîner local"]
  },
  {
    id: "dordogne",
    title: "Dordogne canoë & villages",
    destination: "Vallée de la Dordogne",
    image_url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=80",
    dates: "Dans 2 semaines",
    duration: "2 jours",
    budget_min: 180,
    budget_max: 300,
    physical_level: "facile",
    ambience_tags: ["fun", "rivière", "patrimoine"],
    compatibility_score: 83,
    interested_count: 9,
    status: "Groupe presque complet",
    description: "Un week-end vivant mais accessible, entre canoë doux, village en pierre, marché et repas partagé.",
    activities: ["Canoë", "Village", "Repas local", "Marché"]
  },
  {
    id: "pays-basque",
    title: "Pays basque intérieur",
    destination: "Saint-Jean-Pied-de-Port et montagnes",
    image_url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1600&q=80",
    dates: "Flexible",
    duration: "2 jours",
    budget_min: 200,
    budget_max: 350,
    physical_level: "facile/intermédiaire",
    ambience_tags: ["montagne", "culture locale", "repas"],
    compatibility_score: 91,
    interested_count: 8,
    status: "Nouveau",
    description: "Montagne douce, marché local et ferme partenaire pour une aventure humaine, gourmande et très ancrée dans le territoire.",
    activities: ["Randonnée", "Ferme", "Marché", "Village"]
  }
];

export const mockDestinations: MockDestination[] = [
  {
    id: "vallee-aspe",
    name: "Vallée d'Aspe",
    lat: 42.978,
    lng: -0.596,
    nature_type: ["Montagne", "Vallée"],
    compatible_departure_cities: ["Bordeaux", "Toulouse"],
    approximate_distance: "3h depuis Bordeaux",
    average_budget: 290,
    recommended_physical_level: ["Facile", "Intermédiaire", "facile/intermédiaire"],
    compatible_ambiences: ["Calme & déconnexion", "Découverte locale", "Fun & aventure douce"],
    accessibility: "Train jusqu'à Pau ou Oloron, puis covoiturage de groupe",
    image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1600&q=80",
    safety_score: 92,
    ideal_season: "Printemps à automne",
    region: "Pyrénées-Atlantiques",
    description: "Une vallée de montagne authentique, parfaite pour un week-end nature, local et rassurant."
  },
  {
    id: "pays-basque-interieur",
    name: "Pays basque intérieur",
    lat: 43.164,
    lng: -1.237,
    nature_type: ["Montagne", "Campagne", "Vallée"],
    compatible_departure_cities: ["Bordeaux", "Toulouse"],
    approximate_distance: "2h30 depuis Bordeaux",
    average_budget: 260,
    recommended_physical_level: ["Facile", "Intermédiaire"],
    compatible_ambiences: ["Découverte locale", "Calme & déconnexion", "Premium & confort"],
    accessibility: "Train vers Bayonne puis navette ou covoiturage",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1600&q=80",
    safety_score: 90,
    ideal_season: "Toute l'année",
    region: "Pays basque",
    description: "Montagnes douces, villages, marchés et fermes pour un week-end très ancré localement."
  },
  {
    id: "dordogne",
    name: "Dordogne",
    lat: 44.837,
    lng: 1.214,
    nature_type: ["Rivière", "Campagne"],
    compatible_departure_cities: ["Bordeaux", "Toulouse"],
    approximate_distance: "2h depuis Bordeaux",
    average_budget: 230,
    recommended_physical_level: ["Très facile", "Facile"],
    compatible_ambiences: ["Fun & aventure douce", "Découverte locale"],
    accessibility: "Train régional et covoiturage court",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=80",
    safety_score: 88,
    ideal_season: "Avril à octobre",
    region: "Nouvelle-Aquitaine",
    description: "Rivière, villages, marchés et canoë accessible pour un groupe qui veut du fun doux."
  },
  {
    id: "bassin-arcachon-nature",
    name: "Bassin d'Arcachon nature",
    lat: 44.661,
    lng: -1.168,
    nature_type: ["Mer", "Forêt"],
    compatible_departure_cities: ["Bordeaux"],
    approximate_distance: "1h depuis Bordeaux",
    average_budget: 180,
    recommended_physical_level: ["Très facile", "Facile"],
    compatible_ambiences: ["Calme & déconnexion", "Premium & confort"],
    accessibility: "Train direct depuis Bordeaux",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=80",
    safety_score: 94,
    ideal_season: "Mars à octobre",
    region: "Gironde",
    description: "Mer, pinède, cabanes ostréicoles et marche douce pour une échappée facile."
  },
  {
    id: "fontainebleau",
    name: "Fontainebleau",
    lat: 48.404,
    lng: 2.701,
    nature_type: ["Forêt"],
    compatible_departure_cities: ["Paris"],
    approximate_distance: "50 min depuis Paris",
    average_budget: 70,
    recommended_physical_level: ["Très facile", "Facile"],
    compatible_ambiences: ["Calme & déconnexion", "Découverte locale"],
    accessibility: "Train direct puis marche courte",
    image: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1600&q=80",
    safety_score: 91,
    ideal_season: "Toute l'année",
    region: "Île-de-France",
    description: "Forêt, rochers, pique-nique et retour simple depuis Paris."
  },
  {
    id: "vercors",
    name: "Vercors",
    lat: 45.07,
    lng: 5.45,
    nature_type: ["Montagne", "Forêt"],
    compatible_departure_cities: ["Lyon"],
    approximate_distance: "2h depuis Lyon",
    average_budget: 310,
    recommended_physical_level: ["Intermédiaire"],
    compatible_ambiences: ["Sport & dépassement", "Découverte locale", "Calme & déconnexion"],
    accessibility: "Train vers Grenoble puis covoiturage",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1600&q=80",
    safety_score: 87,
    ideal_season: "Mai à octobre",
    region: "Auvergne-Rhône-Alpes",
    description: "Plateaux, gîtes, fromageries et randonnée pour une aventure plus montagne."
  }
];

export const mockDestinationSeeds: DestinationSeed[] = [
  {
    userId: "jonathan",
    destinationId: "vallee-aspe",
    dates: "Week-end prochain",
    budget: "200 à 350 €",
    physical_level: "Intermédiaire",
    ambience: ["Calme & déconnexion", "Découverte locale"],
    people_wanted: 6
  },
  {
    userId: "lea",
    destinationId: "pays-basque-interieur",
    dates: "Week-end",
    budget: "200 à 350 €",
    physical_level: "Facile",
    ambience: ["Découverte locale"],
    people_wanted: 5
  }
];

export const mockCollectiveIntents: CollectiveIntent[] = [
  {
    nature_type: "Montagne",
    departure_city: "Bordeaux",
    dates: "Week-end",
    budget: "200 à 350 €",
    physical_level: "Facile",
    ambience: ["Calme & déconnexion", "Découverte locale"],
    interested_count: 12
  },
  {
    nature_type: "Forêt",
    departure_city: "Paris",
    dates: "Journée",
    budget: "Moins de 100 €",
    physical_level: "Facile",
    ambience: ["Calme & déconnexion"],
    interested_count: 18
  },
  {
    nature_type: "Rivière",
    departure_city: "Bordeaux",
    dates: "2-3 jours",
    budget: "200 à 350 €",
    physical_level: "Facile",
    ambience: ["Fun & aventure douce"],
    interested_count: 9
  }
];

export const mockLocalActivities: MockLocalActivity[] = [
  {
    id: "aspe-rando",
    destinationId: "vallee-aspe",
    lat: 42.979,
    lng: -0.59,
    name: "Randonnée douce avec point de vue",
    category: "Randonnée",
    duration: "2h30",
    estimated_price: 0,
    physical_level: "Facile",
    ambience: ["Calme & déconnexion", "Découverte locale"],
    weather_compatible: ["soleil", "nuageux"],
    risk: "faible",
    booking_required: false,
    group_friendly: true,
    description: "Une boucle accessible pour respirer et découvrir la vallée sans pression sportive.",
    image: "https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&w=900&q=80",
    source: "mock",
    external_url: "https://www.openstreetmap.org/#map=14/42.979/-0.590"
  },
  {
    id: "aspe-ferme",
    destinationId: "vallee-aspe",
    lat: 42.984,
    lng: -0.61,
    name: "Ferme locale et dégustation",
    category: "Producteur local",
    duration: "1h30",
    estimated_price: 18,
    physical_level: "Très facile",
    ambience: ["Découverte locale", "Calme & déconnexion"],
    weather_compatible: ["soleil", "nuageux", "pluie"],
    risk: "faible",
    booking_required: true,
    group_friendly: true,
    description: "Rencontre avec un producteur et dégustation de fromage local.",
    image: "https://images.unsplash.com/photo-1500595046743-cd271d694d30?auto=format&fit=crop&w=900&q=80",
    source: "mock",
    external_url: "https://www.google.com/search?q=fromagerie+vall%C3%A9e+d%27aspe"
  },
  {
    id: "aspe-diner",
    destinationId: "vallee-aspe",
    lat: 42.982,
    lng: -0.602,
    name: "Dîner béarnais collectif",
    category: "Repas local",
    duration: "2h",
    estimated_price: 32,
    physical_level: "Très facile",
    ambience: ["Découverte locale", "Premium & confort"],
    weather_compatible: ["soleil", "nuageux", "pluie"],
    risk: "faible",
    booking_required: true,
    group_friendly: true,
    description: "Un dîner simple et chaleureux pour créer du lien dans le groupe.",
    image: "https://images.unsplash.com/photo-1551218808-94e220e084d2?auto=format&fit=crop&w=900&q=80",
    source: "mock",
    external_url: "https://www.google.com/search?q=restaurant+b%C3%A9arnais+vall%C3%A9e+d%27aspe"
  },
  {
    id: "aspe-rafting",
    destinationId: "vallee-aspe",
    lat: 42.974,
    lng: -0.58,
    name: "Rafting doux encadré",
    category: "Eau vive",
    duration: "2h",
    estimated_price: 55,
    physical_level: "Intermédiaire",
    ambience: ["Fun & aventure douce"],
    weather_compatible: ["soleil", "nuageux"],
    risk: "moyen",
    booking_required: true,
    group_friendly: true,
    description: "Une sortie dynamique mais accessible, encadrée par un professionnel.",
    image: "https://images.unsplash.com/photo-1508166466920-f65aa51f727c?auto=format&fit=crop&w=900&q=80",
    source: "mock",
    external_url: "https://www.google.com/search?q=rafting+vall%C3%A9e+d%27aspe"
  },
  {
    id: "aspe-cheval",
    destinationId: "vallee-aspe",
    lat: 42.99,
    lng: -0.604,
    name: "Balade à cheval en vallée",
    category: "Cheval",
    duration: "1h30",
    estimated_price: 45,
    physical_level: "Facile",
    ambience: ["Calme & déconnexion"],
    weather_compatible: ["soleil", "nuageux"],
    risk: "faible",
    booking_required: true,
    group_friendly: true,
    description: "Un plan B doux si le groupe préfère éviter l'eau vive.",
    image: "https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?auto=format&fit=crop&w=900&q=80",
    source: "mock",
    external_url: "https://www.google.com/search?q=balade+%C3%A0+cheval+vall%C3%A9e+d%27aspe"
  },
  {
    id: "pb-marche",
    destinationId: "pays-basque-interieur",
    lat: 43.164,
    lng: -1.237,
    name: "Marché local et village",
    category: "Culture locale",
    duration: "2h",
    estimated_price: 10,
    physical_level: "Très facile",
    ambience: ["Découverte locale", "Calme & déconnexion"],
    weather_compatible: ["soleil", "nuageux", "pluie"],
    risk: "faible",
    booking_required: false,
    group_friendly: true,
    description: "Village, produits locaux et rythme doux.",
    image: "https://images.unsplash.com/photo-1519677100203-a0e668c92439?auto=format&fit=crop&w=900&q=80",
    source: "mock",
    external_url: "https://www.google.com/search?q=march%C3%A9+local+pays+basque+int%C3%A9rieur"
  },
  {
    id: "dordogne-canoe",
    destinationId: "dordogne",
    lat: 44.837,
    lng: 1.214,
    name: "Canoë facile sur la rivière",
    category: "Rivière",
    duration: "2h",
    estimated_price: 35,
    physical_level: "Facile",
    ambience: ["Fun & aventure douce"],
    weather_compatible: ["soleil", "nuageux"],
    risk: "moyen",
    booking_required: true,
    group_friendly: true,
    description: "Une activité accessible pour donner de l'énergie au week-end.",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80",
    source: "mock",
    external_url: "https://www.google.com/search?q=cano%C3%AB+dordogne"
  },
  {
    id: "fontainebleau-rochers",
    destinationId: "fontainebleau",
    lat: 48.404,
    lng: 2.701,
    name: "Balade forêt et rochers",
    category: "Forêt",
    duration: "3h",
    estimated_price: 0,
    physical_level: "Facile",
    ambience: ["Calme & déconnexion"],
    weather_compatible: ["soleil", "nuageux"],
    risk: "faible",
    booking_required: false,
    group_friendly: true,
    description: "Une sortie simple depuis Paris, parfaite pour une première rencontre.",
    image: "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=900&q=80",
    source: "mock",
    external_url: "https://www.openstreetmap.org/#map=13/48.404/2.701"
  }
];

export const mockMembers: MockMember[] = [
  {
    id: "jonathan",
    name: "Jonathan",
    age: "32 ans",
    city: "Bordeaux",
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80",
    physical_level: "Intermédiaire",
    preferred_ambience: ["Calme & déconnexion", "Découverte locale"],
    budget: "200 à 350 €",
    availability: ["Week-end"],
    preferred_nature: ["Montagne"],
    trust_badges: ["profil vérifié", "organise la seed Vallée d'Aspe"]
  },
  {
    id: "sofia",
    name: "Sofia",
    age: "28 ans",
    city: "Bordeaux",
    photo: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=600&q=80",
    physical_level: "Facile",
    preferred_ambience: ["Calme & déconnexion"],
    budget: "200 à 350 €",
    availability: ["Week-end"],
    preferred_nature: ["Montagne", "Forêt"],
    trust_badges: ["profil vérifié", "petits groupes"]
  },
  {
    id: "mehdi",
    name: "Mehdi",
    age: "30 ans",
    city: "Bordeaux",
    photo: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80",
    physical_level: "Intermédiaire",
    preferred_ambience: ["Fun & aventure douce", "Découverte locale"],
    budget: "200 à 350 €",
    availability: ["Week-end", "2-3 jours"],
    preferred_nature: ["Montagne", "Rivière"],
    trust_badges: ["fiable", "3 Trips"]
  }
];

export const destination: Destination = {
  id: "vallee-aspe",
  name: "Vallée d'Aspe",
  region: "Pyrénées-Atlantiques",
  country: "France",
  lat: 42.978,
  lng: -0.596,
  description: "Une vallée de montagne authentique, idéale pour un week-end nature, avec randonnées accessibles, villages, fermes, activités d'eau vive et repas locaux.",
  best_season: "Avril à octobre",
  access_info: "Train jusqu'à Pau ou Oloron-Sainte-Marie, puis covoiturage de groupe organisé dans la Trip."
};

export const members: UserProfile[] = [
  {
    id: "sarah",
    name: "Sarah",
    age_range: "29 ans",
    city: "Bordeaux",
    photo_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=600&q=80",
    bio: "Envie de nature, de calme et de bons paysages, sans courir après la performance.",
    verified: true,
    physical_level: "facile",
    budget_range: "200 à 350 €",
    adventure_style: "Calme et contemplation",
    preferred_ambiences: ["nature", "calme", "découverte locale"],
    safety_preferences: ["Profils vérifiés", "Petit groupe", "Groupe calme et respectueux"],
    past_trips: 2,
    badges: ["profil vérifié", "rythme doux"]
  },
  {
    id: "amine",
    name: "Amine",
    age_range: "31 ans",
    city: "Paris",
    photo_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80",
    bio: "Partant pour marcher, bien manger local et partager un week-end simple avec un bon groupe.",
    verified: true,
    physical_level: "facile/intermédiaire",
    budget_range: "200 à 350 €",
    adventure_style: "Nature et repas local",
    preferred_ambiences: ["randonnée facile", "paysages", "repas local"],
    safety_preferences: ["Référent de Trip", "Activités encadrées"],
    past_trips: 3,
    badges: ["fiable", "3 Trips"]
  },
  {
    id: "lea",
    name: "Léa",
    age_range: "34 ans",
    city: "Toulouse",
    photo_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80",
    bio: "J'aime les villages, les producteurs et les aventures bien organisées mais pas rigides.",
    verified: true,
    physical_level: "intermédiaire",
    budget_range: "flexible",
    adventure_style: "Découverte locale",
    preferred_ambiences: ["marchés", "villages", "fermes"],
    safety_preferences: ["Petit groupe", "Charte claire"],
    past_trips: 5,
    badges: ["référente", "avis 4.9"]
  },
  {
    id: "nora",
    name: "Nora",
    age_range: "27 ans",
    city: "Nantes",
    photo_url: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=600&q=80",
    bio: "Besoin de déconnexion, de paysages et d'un groupe doux où chacun a son rythme.",
    verified: false,
    physical_level: "facile",
    budget_range: "100 à 200 €",
    adventure_style: "Slow life",
    preferred_ambiences: ["déconnexion", "paysages", "calme"],
    safety_preferences: ["Groupe mixte", "Groupe calme et respectueux"],
    past_trips: 1,
    badges: ["nouvelle", "slow life"]
  }
];

export const activities: Activity[] = [
  {
    id: "rando-panorama",
    name: "Randonnée panoramique facile",
    destination_id: "vallee-aspe",
    category: "Randonnées",
    sub_category: "Point de vue",
    lat: 42.979,
    lng: -0.59,
    duration_estimate: "2h30",
    price_min: 0,
    price_max: 0,
    physical_level: "facile",
    risk_level: "faible",
    weather_dependency: true,
    seasonality: "printemps à automne",
    group_size_min: 3,
    group_size_max: 12,
    booking_required: false,
    professional_supervision_required: false,
    ambience_tags: ["paysages", "calme", "nature"],
    good_for: ["groupe calme", "première randonnée", "déconnexion"],
    source: "OpenStreetMap / Overpass API simulée",
    confidence_score: 91
  },
  {
    id: "fromagerie",
    name: "Ferme locale et fromagerie",
    destination_id: "vallee-aspe",
    category: "Fermes et producteurs",
    sub_category: "Produit local",
    lat: 42.984,
    lng: -0.61,
    duration_estimate: "1h30",
    price_min: 10,
    price_max: 25,
    physical_level: "très facile",
    risk_level: "faible",
    weather_dependency: false,
    seasonality: "toute l'année",
    group_size_min: 4,
    group_size_max: 10,
    booking_required: true,
    professional_supervision_required: false,
    ambience_tags: ["local", "authentique", "découverte"],
    good_for: ["pluie", "lien de groupe", "repas local"],
    source: "DATAtourisme simulé",
    confidence_score: 88
  },
  {
    id: "rafting",
    name: "Rafting doux accompagné",
    destination_id: "vallee-aspe",
    category: "Activités eau vive",
    sub_category: "Rafting initiation",
    lat: 42.974,
    lng: -0.58,
    duration_estimate: "2h",
    price_min: 45,
    price_max: 70,
    physical_level: "intermédiaire",
    risk_level: "moyen",
    weather_dependency: true,
    seasonality: "mai à septembre",
    group_size_min: 4,
    group_size_max: 8,
    booking_required: true,
    professional_supervision_required: true,
    ambience_tags: ["fun", "sortie de zone de confort", "rivière"],
    good_for: ["énergie de groupe", "activité encadrée"],
    source: "Google Places API officielle simulée",
    confidence_score: 84
  },
  {
    id: "poterie",
    name: "Atelier poterie de montagne",
    destination_id: "vallee-aspe",
    category: "Artisanat",
    sub_category: "Atelier créatif",
    lat: 42.99,
    lng: -0.604,
    duration_estimate: "2h",
    price_min: 25,
    price_max: 50,
    physical_level: "très facile",
    risk_level: "faible",
    weather_dependency: false,
    seasonality: "toute l'année",
    group_size_min: 3,
    group_size_max: 8,
    booking_required: true,
    professional_supervision_required: false,
    ambience_tags: ["calme", "créatif", "local"],
    good_for: ["pluie", "slow life", "discussion"],
    source: "Office de tourisme simulé",
    confidence_score: 82
  },
  {
    id: "diner",
    name: "Dîner béarnais partagé",
    destination_id: "vallee-aspe",
    category: "Repas local",
    sub_category: "Restaurant",
    lat: 42.982,
    lng: -0.602,
    duration_estimate: "2h",
    price_min: 24,
    price_max: 38,
    physical_level: "très facile",
    risk_level: "faible",
    weather_dependency: false,
    seasonality: "toute l'année",
    group_size_min: 4,
    group_size_max: 12,
    booking_required: true,
    professional_supervision_required: false,
    ambience_tags: ["convivial", "local", "rencontre amicale"],
    good_for: ["créer du lien", "arrivée du groupe"],
    source: "Prestataire partenaire simulé",
    confidence_score: 93
  }
];

export const providers: Provider[] = [
  {
    id: "guide-aspe",
    name: "Guides Nature Aspe",
    category: "Guide randonnée",
    location: "Bedous",
    website: "https://exemple-guide-aspe.fr",
    phone: "+33 6 00 00 00 00",
    verified: true,
    activities: ["Randonnée douce", "Lecture de paysage"]
  },
  {
    id: "ferme-loustaou",
    name: "Ferme Loustaou",
    category: "Ferme et fromagerie",
    location: "Vallée d'Aspe",
    website: "https://exemple-ferme.fr",
    phone: "+33 5 00 00 00 00",
    verified: true,
    activities: ["Visite", "Dégustation"]
  }
];

export const itinerary: ItineraryItem[] = [
  { id: "i1", trip_id: "aspe", day: "Vendredi soir", time: "19:30", title: "Arrivée et installation", description: "Installation au gîte, dîner simple et rencontre du groupe.", duration: "2h" },
  { id: "i2", trip_id: "aspe", day: "Samedi matin", time: "09:30", title: "Randonnée douce avec point de vue", description: "Balade accessible pour prendre l'air sans pression.", activity_id: "rando-panorama", duration: "2h30", alternative_if_rain: "Atelier poterie" },
  { id: "i3", trip_id: "aspe", day: "Samedi midi", time: "12:30", title: "Pique-nique ou repas local", description: "Pause simple pour créer du lien.", duration: "1h30" },
  { id: "i4", trip_id: "aspe", day: "Samedi après-midi", time: "15:00", title: "Ferme locale ou atelier artisanal", description: "Découverte d'un producteur local, avec plan B créatif si pluie.", activity_id: "fromagerie", duration: "2h", alternative_if_rain: "Atelier poterie" },
  { id: "i5", trip_id: "aspe", day: "Samedi soir", time: "20:00", title: "Dîner local", description: "Un moment convivial pour se sentir vraiment en groupe.", activity_id: "diner", duration: "2h" },
  { id: "i6", trip_id: "aspe", day: "Dimanche matin", time: "10:00", title: "Rafting doux si météo favorable", description: "Activité encadrée par un professionnel. Alternative : balade à cheval ou visite de village.", activity_id: "rafting", duration: "2h", alternative_if_rain: "Visite de village et marché couvert" },
  { id: "i7", trip_id: "aspe", day: "Dimanche après-midi", time: "14:30", title: "Balade courte, bilan du groupe et retour", description: "Dernier bol d'air avant de rentrer.", duration: "2h" }
];

export const votes: Vote[] = [
  { id: "v1", trip_id: "aspe", user_id: "sarah", activity_id: "rando-panorama", vote_value: 92 },
  { id: "v2", trip_id: "aspe", user_id: "amine", activity_id: "fromagerie", vote_value: 86 },
  { id: "v3", trip_id: "aspe", user_id: "lea", activity_id: "rafting", vote_value: 63 },
  { id: "v4", trip_id: "aspe", user_id: "nora", activity_id: "poterie", vote_value: 74 },
  { id: "v5", trip_id: "aspe", user_id: "sarah", activity_id: "diner", vote_value: 95 }
];

export const reviews: Review[] = [
  { id: "r1", reviewer_id: "amine", reviewed_user_id: "lea", trip_id: "vercors", rating: 5, comment: "Très bonne énergie de groupe, attentive au rythme de chacun." },
  { id: "r2", reviewer_id: "sarah", reviewed_user_id: "amine", trip_id: "fontainebleau", rating: 5, comment: "Fiable, chaleureux, pas dans la performance." }
];
